apiVersion: v1
kind: Service
metadata:
  name: compliantai-service
spec:
  type: NodePort
  selector:
    app: compliantai
  ports:
    - #port: 80  # uncomment for GKE
      port: 5001  # comment for GKE
      targetPort: 5001
      nodePort: 30080  # comment for GKE
