apiVersion: v1
kind: Service
metadata:
  name: compliantai-service
spec:
  type: NodePort
  selector:
    app: compliantai
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30080  # comment for GKE
