models:
  default: llama3:8b
  endpoint: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 4096

databases:
  esg_db:
    type: faiss
    collection: platform
    embedding_model: nomic-embed-text
    dimension: 768
    index_path: ./databases/esg_db.index
    mapping_path: ./databases/esg_db_mapping.json
  finra_db:
    type: faiss
    collection: platform
    embedding_model: nomic-embed-text
    dimension: 768
    index_path: ./databases/esg_db.index
    mapping_path: ./databases/esg_db_mapping.json
  gdpr_db:
    type: faiss
    collection: platform
    embedding_model: nomic-embed-text
    dimension: 768
    index_path: ./databases/esg_db.index
    mapping_path: ./databases/esg_db_mapping.json

  esg_graph_db:
    uri: bolt://localhost:7687
    user: neo4j
    password: neo4j
  
  finra_graph_db:
    uri: bolt://localhost:7687
    user: neo4j
    password: neo4j
  
  gdpr_graph_db:
    uri: bolt://localhost:7687
    user: neo4j
    password: neo4j

document_processor:
  embedding_model: nomic-embed-text
  chunking_profiles:
    default:
      strategy: recursive
      separators:
        - "\n\n"
        - "\n"
        - " "
      chunk_size: 1000
      chunk_overlap: 200
      metadata_headers: ["chunk_id"]
    esg:
      strategy: recursive
      separators:
        - "\n\n"
        - "\nREQUIREMENTS\n"
        - "\nRECOMMENDATIONS\n"
        - "\nGUIDANCE\n"
        - "\n"
        - " "
      chunk_size: 1200
      chunk_overlap: 300
      metadata_headers:
        - chunk_id
        - summary
        - standard
        - requirements
        - recommendations
        - guidance
        - metrics
        - entities
    finra:
      strategy: recursive
      separators:
        - "\n\n"
        # - "\nREQUIREMENTS\n"
        # - "\nRECOMMENDATIONS\n"
        # - "\nGUIDANCE\n"
        - "\n"
        - " "
      chunk_size: 1200
      chunk_overlap: 300
      metadata_headers:
        - chunk_id
        - summary
        - standard
        # - requirements
        # - recommendations
        # - guidance
        # - metrics
        # - entities
    gdpr:
      strategy: recursive
      separators:
        - "\n\n"
        # - "\nREQUIREMENTS\n"
        # - "\nRECOMMENDATIONS\n"
        # - "\nGUIDANCE\n"
        - "\n"
        - " "
      chunk_size: 1200
      chunk_overlap: 300
      metadata_headers:
        - chunk_id
        - summary
        - standard
        # - requirements
        # - recommendations
        # - guidance
        # - metrics
        # - entities